package com.saothienhat
 
import com.saothienhat.DroolsTest.Message;
import com.saothienhat.services.DroolsLogger;
 
rule "Hello World"
    when
        m : Message( status == Message.HELLO, myMessage : message )
    then
        System.out.println( myMessage );
        m.setMessage( "Goodbye cruel world" );
        m.setStatus( Message.GOODBYE );
        DroolsLogger.logDroolsInfo(drools, "LOGGER here !");
        
        update( m );
end

rule "GoodBye"
    when
        Message( status == Message.GOODBYE, myMessage : message )
    then
        System.out.println( myMessage );
end
